apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-hub-schema
spec:
  selector:
    matchLabels:
      app: event-hub-schema
      tier: validator
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: event-hub-schema
        tier: validator
        track: stable
    spec:
      containers:
        - name: event-hub-schema
          image: "gcr.io/event-hub-249001/event-hub-schema:0.0.1-SNAPSHOT"
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: 8080
